INSERT INTO ROOM (ROOM_NUMBER, NAME, BED_INFO)
VALUES ('P1', 'Piccadilly', '1 Queen Bed');

INSERT INTO ROOM (ROOM_NUMBER, NAME, BED_INFO)
VALUES ('P2', 'Piccadilly', '2 Double Beds');

INSERT INTO ROOM (ROOM_NUMBER, NAME, BED_INFO)
VALUES ('A1', 'Atlantic', '1 King Bed');

INSERT INTO ROOM (ROOM_NUMBER, NAME, BED_INFO)
VALUES ('B1', 'Blue Lagoon', '1 Single Bed');

INSERT INTO RESERVATION
(ROOM_ID, GUEST_FIRST_NAME, GUEST_LAST_NAME, DATE)
VALUES
(1, 'Berru', 'Hanedar', '2026-07-20');

INSERT INTO RESERVATION
(ROOM_ID, GUEST_FIRST_NAME, GUEST_LAST_NAME, DATE)
VALUES
(2, 'Ahmet', 'Yılmaz', '2026-07-22');

INSERT INTO RESERVATION
(ROOM_ID, GUEST_FIRST_NAME, GUEST_LAST_NAME, DATE)
VALUES
(3, 'Ayşe', 'Demir', '2026-07-25');