DROP TABLE IF EXISTS RESERVATION;
DROP TABLE IF EXISTS ROOMS;

CREATE TABLE ROOMS (
    ROOM_ID UUID PRIMARY KEY,
    NAME VARCHAR(64) NOT NULL,
    NUMBER VARCHAR(16) NOT NULL,
    BED_INFO VARCHAR(64)
);